[book]
authors = ["Ankitects Pty Ltd 及其他貢獻者"]
language = "zh-tw"
multilingual = false
src = "src"
title = "Anki 使用手冊"

[build]
create-missing = true

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
git-repository-url = "https://github.com/doomnor/anki-manual"
additional-css = ["css/kbd.css"]

[output.linkcheck]
optional = true
warning-policy = "warn"
follow-web-links = true
exclude = [ 'microsoft.com' ]

[output.html.fold]
enable = true
level = 0